# Uncomment this file to enable multilanguage site support

[en]
languageName = "English"
languagedirection = "ltr"
title = "Grey's Blog"
weight = 1

[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "马路的小站"
weight = 1

