# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Grey0520"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/Grey0520"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "jianshu"
name = "简书"
url = "https://www.jianshu.com/u/67c77b3a585b"

